GET http://localhost:3001/api/persons/4

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Sumanth",
    "number": "9392769077"
}

###
POST https://phonebook-0uwq.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Sumanth",
    "number": "9392769077"
}

###
GET https://phonebook-0uwq.onrender.com/api/persons

###

DELETE http://localhost:3001/api/persons/650daa6a3e423ddf9ed9658f
###
GET http://localhost:3001/api/persons